version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app  # Bind mount for hot code updates
    ports:
      - "5000:5000"
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - FLASK_ENV=development
